name: Rust

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  security_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Salus
      run: docker run --rm -t -v $(pwd):/home/repo coinbase/salus

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Musl tools
      run: sudo apt install --yes musl-tools musl-dev musl
    - name: Get Rust Musl
      run: rustup target add x86_64-unknown-linux-musl
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
